baseURL = 'https://samoyed24.github.io/'
title = "萨摩耶的个人博客"
theme = 'hugo-theme-stack'
enableRobotsTXT = true

defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

pagination.pagerSize = 5

[permalinks]
  post = "/posts/:slug/"

[params]
  mainSections = ["posts"]
  description = "个人技术博客"
  rssFullContent = true

  [params.footer]
    since = 2026

  [params.sidebar]
    emoji = "✍️"
    subtitle = "记录技术学习与实践的随笔"

  [params.widgets]
    homepage = [
      { type = "search" },
      { type = "archives", params = { limit = 10 } },
      { type = "categories", params = { limit = 10 } },
      { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

  [params.comments]
    enabled = false

  [params.cookies]
    enabled = false

[[menu.main]]
  identifier = 'posts'
  name = '博客'
  url = '/posts/'
  weight = 1
[[menu.main]]
  identifier = 'search'
  name = '搜索'
  url = '/search/'
  weight = 2
[[menu.main]]
  identifier = 'archives'
  name = '归档'
  url = '/archives/'
  weight = 3

[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/samoyed24'
  weight = 1
  [menu.social.params]
    icon = 'brand-github'
    newTab = true
